version: '3'
services:
  app:
    build: ../  
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password  
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_DRIVER=org.postgresql.Driver  
      - JPA_DDL=update
      - JPA_DIALECT=org.hibernate.dialect.PostgreSQLDialect

  db:
    build: ../db
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/data/db
volumes:
  dbdata: